### PR TITLE
ES6 Ideas

### PR DESCRIPTION
**Pull request by stephenmelnicki**
Just a quick, rough outline of some of the basic ES6 ideas. Current plan is to write up some slides using these ideas to provide a quick primer on some of, what I think are, the most important changes with ES6.

Let me know what you think and whether some of these might need to be expanded on or otherwise.

@westeezy

### CODE REVIEW

**Comment by westeezy** [comment]
I would say we don't need the Katas. I am actually already building a set of katas based on those same ones you got from the ES6 katas site from the same sections actually so I'll update the readme with those when they are done.

**Comment by westeezy** [comment]
Other than that looks great. I'll merge once you pull out the Katas. I might move this to a better directory in the coming weeks as I restructure(still gonna keep putting everythign in this readme until after all content is present so this is good for now). And once I finish up the katas we can touchbase if theres anything you want to add etc. Should be finishing some ES6 and React ones tomorrow so we can chat during the week. 

Thanks for taking the time to add some content!!

**Comment by stephenmelnicki** [comment]
@westeezy Cool! Done and done. 

I've removed the ES6 katas and brought this up to date with the latest changes to `seattle` branch. 

Give it another gander when you've got some time and let me know if you'd like for me to make any other changes.

I'll start working on some slides in the meantime.

**Comment by westeezy** [comment]
Okay sweet. Yeah I'm gonna merge this in and then start moving some stuff around this afternoon/evening. Thanks!!

**Pull request merged**
